name: deploy

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  REGISTRY: nicolaiarocci/webday2023
  TAG: blazorapp

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build test image and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}:${{ env.TAG }}

