name: deploy

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  REGISTRY: nicolaiarocci/webday2023
  TAG: blazorapp

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build test image and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}:${{ env.TAG }}

  test:
    needs: docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install Playwright CLI
      run: dotnet tool install --global Microsoft.Playwright.CLI
    - name: Install Browsers
      run: playwright install --with-deps
    - name: Take a nap
      run: sleep 60
    - name: Test
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: dotnet test --no-build --verbosity normal -- Playwright.LaunchOptions.SlowMo=2000
